var News = {
	
	contents: [
        {img: 'news-1.jpg', title:'Lowrider transport is played', data:'16.06.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design.' },
		{img: '', title:'Server news', data:'11.05.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design.Server news, latest updates, cool design. Server news, latest updates, cool design.' },
        {img: '', title:'Latest updates', data:'11.05.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design.' },
        {img: '', title:'Cool design', data:'11.05.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design.' },
        {img: 'news-3.gif', title:'Crazy admins', data:'11.05.2021', text:'ATTENTION! ATTENTION! ATTENTION! admins are crazy. Stay at home, avoid popular places and a lot of people! admins are crazy. Stay at home, avoid popular places and a lot of people! admins are crazy. Stay at home, avoid popular places and a lot of people!' },
        {img: '', title:'Server news', data:'11.05.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design.' },
        {img: '', title:'Latest updates', data:'11.05.2021', text:'Server news, latest updates, cool design.' },
        {img: '', title:'Cool design', data:'11.05.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design.' },
        {img: 'news-2.gif', title:'Crazy admins', data:'11.05.2021', text:'Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design. Server news, latest updates, cool design.' },
        {img: '', title:'Lowrider transport is played', data:'11.05.2021', text:'Server news, latest updates, cool design. ' },
        {img: '', title:'Server news', data:'11.05.2021', text:'Server news, latest updates, cool design.' }
    ],
};